### ISSUE TITLE
bbox issue

### ISSUE THREAD

**Issue by HanOostdijk** [angela-li/sotmus-r#1]
Remark about https://github.com/angela-li/sotmus-r/blob/master/notebooks/sotmus-r-complete.html

`opq(bbox = c("42.255192,-83.287959,42.450232,-82.9104391")) # Also produces the same thing`
does **not** produce the same thing: see the NA's in $bbox (in the html)

You could have used (notice ordering):
`opq(bbox = c(-83.287959,42.255192,-82.9104391,42.450232))`

**Comment by angela-li** [comment]
Ah, thank you! Fixed in 0d6e2dd7d58b7fdd6548f400a0fe2ce0e0e3bfb7.
